### ISSUE TITLE
Unable to reproduce in controlled env from the solution

### ISSUE THREAD

**Issue by breachlabs-org** [S1lkys/SharpKiller#1]
Hello @S1lkys thanks for your research

I'm having a peculiar issue, on my development machine, where defender is completely disable, i'm able to exert the tool and reproduce your demo. Meaning that the AMSI patching works as intended on that machine.

However, on a Windows 10 machine with defender enabled, i'm unable to reproduce.

- I have compiled via VS2022, with the provided solution, and it works on the DEV machine but not the TARGET machine.
- The provided binary from the project also works in the TARGET machine. 

**This is my TARGET machine (i waited a good five minutes)**
- Compiled from the 1.1 Project in VSStudio2022

![image](https://github.com/S1lkys/SharpKiller/assets/143645246/d0de82da-ea34-4d0f-800a-2b492ef21e1c)

**This is my DEV machine (worked instantly)**
- Compiled from the 1.1 Project in VSStudio2022

![image](https://github.com/S1lkys/SharpKiller/assets/143645246/05f7d8b3-052e-4068-b644-557b9f337384)

**This is my TARGET machine (with the pre-compiled binary you provided**

![image](https://github.com/S1lkys/SharpKiller/assets/143645246/ebbe0258-364e-4bd7-8b41-00ef2f28c73f)

Any dependencies i should be aware in the other machine that are missing? 

![image](https://github.com/S1lkys/SharpKiller/assets/143645246/2bdb912d-b1bb-455f-9332-efb194b5ba2d)

Thanks!

**Comment by S1lkys** [comment]
Hi,

please try to set your platform explicitly to x64 in Build > configuration manager
![image](https://github.com/S1lkys/SharpKiller/assets/40408435/26b9b63a-a61e-44eb-b918-0817743ca329)

**Comment by breachlabs-org** [comment]
That was exactly it, thank you very much
