### ISSUE TITLE
Suppor for Process 64 bits

### ISSUE THREAD

**Issue by douglashsilva** [S1lkys/SharpKiller#2]
It only works for 32-bit processes, what would it be like for 64-bit processes?

**Comment by S1lkys** [comment]
For me it doesnt work for 32-bit processes at all and only for 64-Bit. Did you set your compile Flags accordingly to the ReadMe? What are your PC stats?

**Comment by douglashsilva** [comment]
My question is the following, if I want to block amsi in a 64bit process, will it work?
